config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "/home/about", to: "homes#about"
  get "/search", to: "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:create,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'posts_on_date' => 'users#posts_on_date'
  end

  resources :chats, only: [:show, :create, :destroy]

  resources :groups, only: [:index, :show, :new, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }
  has_many :read_counts, dependent: :destroy

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } #今週
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } # 先週
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : "no_image.jpg"
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  def include_user?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    # class_name: "User"でUserモデルを参照
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :read_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy


  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  has_one_attached :profile_image
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    # 空の配列を定義しています。この配列には投稿された本の数を１日ずつ追加します。
    @this_week_book_counts = []
    6.downto(0) do |n|
      # pushメソッドは配列に要素を追加するメソッド
      # pushの引数にn日前に投稿された本の数を渡し、@this_week_book_counts配列に追加しています！
      @this_week_book_counts.push(@books.where(created_at: n.day.ago.all_day).count)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def posts_on_date
    # リクエストの中からユーザーIDを取得し、データベースからユーザー情報を取得
    user = User.includes(:books).find(params[:user_id])
    # リクエストの中から指定された日付を取得し、日付オブジェクトに変換
    date = Date.parse(params[:created_at])
    # ユーザーが指定した日に投稿した本（books）をデータベースから検索
    @books = user.books.where(created_at: date.all_day)
    # 検索結果を表示するためのビュー（posts_on_date_form）にデータを送る
    render :posts_on_date_form
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookcomments_helper.rb
module BookcommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>

        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>

        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class="row">
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user, options: { class: ""} %></td>
  <% end %>

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <td><%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %></td>
  <% end %>
</div>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_posts_on_date_form.html.erb
<div class="row my-3">
  <div class="col-auto">
    <!-- フォームを生成 -->
    <%= form_with url: user_posts_on_date_path(user), method: :get, local: false do |f| %>
      <!-- 入力フィールドと送信ボタンをグループ化 -->
      <div class="input-group">
        <!-- 日付を選択する入力フィールド -->
        <%= f.date_field :created_at, class: "form-control" %>
        <!-- 送信ボタンを表示 -->
        <div class="input-group-append">
          <%= f.submit "検索", class: "btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 検索結果を表示するためのコンテナ -->
<div class="posts_on_date_table mb-2"></div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local: true do |f| %>
      <%= render 'layouts/errors', obj: @user %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>

     <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>

      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>

  </div>
</div>

app/views/users/posts_on_date_form.js.erb
$('.posts_on_date_table').html(`
  <h3>検索結果</h3>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <!--指定した日の記録を表示（非同期通信化）-->
      <%= render "posts_on_date_form", user: @user %>

      <h3>投稿数の前日比・先週比</h3>
      <div class="table_container">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td><!-- 今日の投稿数を表示 -->
              <td><%= @yesterday_book.count %></td><!-- 前日の投稿数を表示 -->
              <td>
                <% if @yesterday_book.count == 0 %>
                  前日の投稿はありません
                <% else %>
                  <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
                  <%= (@the_day_before * 100).round %> %<!-- 前日比を計算し、パーセントで表示 -->
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table_container">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>先週の投稿数</th>
              <th>先週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td><!-- 今週の投稿数を表示 -->
              <td><%= @last_week_book.count %></td><!-- 先週の投稿数を表示 -->
              <td>
                <% if @last_week_book.count == 0 %>
                  先週の投稿はありません
                <% else %>
                  <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
                  <%= (@the_week_before * 100).round %> %<!-- 先週比を計算し、パーセントで表示 -->
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h4>7日分の投稿数</h4>
      <table class="table table-bordered">
        <thead>
          <tr>
            <% (6.downto(0)).each do |n| %>
              <th><%= n == 0 ? "今日" : "#{n}日前" %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% (6.downto(0)).each do |n| %>
              <td><%= @books.where(created_at: n.day.ago.all_day).count %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <canvas id="postCountChart"></canvas>
      <script>
        // ページが読み込まれたときの処理
        $(document).on('turbolinks:load', function() {
          // グラフを描画するためのCanvas要素を取得
          var ctx = document.getElementById("postCountChart");

          // Chart.jsを使ってグラフを作成
          var postCountChart = new Chart(ctx, {
            type: 'line', // type: 'line'で折れ線グラフ(ラインチャート)を使用

            data: {
              // グラフのラベル（x軸の値）
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],

              datasets: [
                {
                  // データセットのラベル
                  label: '投稿した本の数',

                  // データセットの値
                  data: <%= @this_week_book_counts %>,

                  // グラフの線の色（緑）
                  borderColor: "rgba(0, 255, 0, 1)",

                  // グラフの背景色（透明）
                  backgroundColor: "rgba(0, 0, 0, 0)",

                  // グラフの曲線の滑らかさ（0から1の範囲で設定。数値が大きくなるほど曲線が滑らかになる）
                  tension: 0.3
                }
              ],
            },

            options: {
              title: {
                // グラフのタイトル表示
                display: true,
                text: '7日間の投稿数の比較'
              },

              responsive: true, // グラフのレスポンシブデザインを有効化

              scales: {
                y: {
                  // y軸（縦軸）の設定。設定しないと自動になるので書かなくても良い。
                  suggestedMin: 0, // 最小値を0に設定
                  suggestedMax: 10 // 最大値を10に設定
                },
              },
            }
          });
        });
      </script>

    </div>
  </div>
</div>